export const types = {
  //for filterReducer
  FILTER_ACC_AGE: "FILTER_ACC_AGE",
  FILTER_ACC_COST: "FILTER_ACC_COST",
  AGES_WATCHER: "AGES_WATCHER",
  COSTS_WATCHER: "COSTS_WATCHER",
  //for optionsReducer
  UPDATE_COST_OPTIONS: "UPDATE_COST_OPTIONS",
  UPDATE_AGE_OPTIONS: "UPDATE_AGE_OPTIONS",
};
