export const types = {
  FILTER_FOR_AGE: "FILTER_FOR_AGE",
  DARK: "DARK",
  FEUDAL: "FEUDAL",
  CASTLE: "CASTLE",
  IMPERIAL: "IMPERIAL",
  REMOVE_AGE: "REMOVE_AGE",
  ALL_AGES: "ALL_AGES",
  FILTER_FOR_COST: "FILTER_FOR_COST",
  FOOD_COST: "FOOD_COST",
  WOOD_COST: "WOOD_COST",
  GOLD_COST: "GOLD_COST",
  REMOVE_COST: "REMOVE_COST",
};
